# Generated by Django 3.0.5 on 2020-05-10 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laskuser',
            name='is_activated',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Passed activation?'),
        ),
        migrations.AddField(
            model_name='laskuser',
            name='send_messages',
            field=models.BooleanField(default=True, verbose_name='Send you a notification about new comments?'),
        ),
    ]
