# Generated by Django 3.0.5 on 2020-04-21 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20200421_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='confirm_flag',
        ),
    ]
