# Generated by Django 3.0.5 on 2020-05-11 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20200510_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laskuser',
            name='send_messages',
            field=models.BooleanField(default=True, verbose_name='Send you a notification?'),
        ),
    ]
