# Generated by Django 3.0.5 on 2020-07-25 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20200608_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='description',
            field=models.TextField(blank=True, default='Currently no description available', max_length=255),
        ),
    ]
