# Generated by Django 3.0.5 on 2020-05-28 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_remove_question_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='author',
            new_name='user',
        ),
    ]
